//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flat()
        {
            this.CustomerInProjects = new HashSet<CustomerInProject>();
            this.SupplierInProjects = new HashSet<SupplierInProject>();
        }
    
        public int Id { get; set; }
        public string Floor { get; set; }
        public Nullable<int> FlatNumber { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> ProjecId { get; set; }
        public Nullable<bool> HasElevator { get; set; }
        public Nullable<int> SquareMeter { get; set; }
        public string Comment { get; set; }
        public Nullable<int> RoomsCount { get; set; }
        public string AirDirections { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInProject> CustomerInProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierInProject> SupplierInProjects { get; set; }
        public virtual Project Project { get; set; }
    }
}
