//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentItems = new HashSet<PaymentItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CustomerInProjectId { get; set; }
        public Nullable<int> SupplierInProjectId { get; set; }
        public Nullable<int> PaymentRelationId { get; set; }
        public Nullable<int> ChequeNumber { get; set; }
        public Nullable<System.DateTime> ChequeDueDate { get; set; }
        public Nullable<System.DateTime> CreditValidity { get; set; }
        public Nullable<int> CreditNumber { get; set; }
        public Nullable<int> CreditPaymentsNumber { get; set; }
        public Nullable<bool> WithVat { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual CustomerInProject CustomerInProject { get; set; }
        public virtual SupplierInProject SupplierInProject { get; set; }
        public virtual PaymentRelation PaymentRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentItem> PaymentItems { get; set; }
    }
}
