//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentItem
    {
        public int Id { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> DebtId { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsRefuned { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Debt Debt { get; set; }
    }
}
