//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.SupplierInProjects = new HashSet<SupplierInProject>();
        }
    
        public int Id { get; set; }
        public string TZ { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Street { get; set; }
        public Nullable<int> HouseNumber { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CNPJ { get; set; }
        public string Comment { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierInProject> SupplierInProjects { get; set; }
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
